SELECT EMP_NAME, EMP_NO, DEPT_CODE, SALARY, EMAIL, BONUS

FROM EMPLOYEE

WHERE DEPT_CODE='D9' OR DEPT_CODE='D6' AND SALARY > 3000000

AND EMAIL LIKE '____%' AND BONUS IS NULL;

SELECT EMP_NAME, EMP_NO, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D9', 'D6') AND SALARY >= 3000000 AND BONUS IS NOT NULL
    AND SUBSTR(EMP_NO, 8, 1) IN (1, 3) AND EMAIL LIKE '___/_%' ESCAPE '/';
    
SELECT *
FROM EMPLOYEE
WHERE BONUS IS NULL AND MANAGER_ID IS NOT NULL;

-------------------------------------------------------------

SELECT DEPT_CODE, SUM(SALARY) 합계, FLOOR(AVG(SALARY)) 평균, COUNT(*) 인원수

FROM EMPLOYEE

GROUP BY DEPT_CODE

HAVING FLOOR(AVG(SALARY)) > 2800000

ORDER BY DEPT_CODE ASC;

-----------------------------------------------------------------

SELECT ROWNUM, E.*

FROM (SELECT EMPNAME, SAL
        FROM EMP
        WHERE SAL IS NOT NULL
        ORDER BY SAL DESC) E

WHERE ROWNUM <= 3;

----------------------------------------------------------------------

CREATE USER EMP IDENTIFIED BY EMP0123; 

CREATE TABLE DEPARTMENT(

    DEPTCODE NUMBER PRIMARY KEY,

    DEPTNAME NVARCHAR2(10) NOT NULL

);



CREATE TABLE EMPLOYEE(

EMPNO NUMBER PRIMARY KEY,

EMPNAME VARCHAR2(10) NOT NULL,

DEPTNO NUMBER REFERENCES DEPARTMENT(DEPTCODE)

);

SELECT EMPNO, EMPNAME, DEPTNO, DEPTNAME

FROM EMPLOYEE

JOIN DEPARTMENT USING(DEPTNO);