--01.
INSERT INTO TB_CLASS_TYPE VALUES ('01', '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES ('02', '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES ('03', '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES ('04', '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES ('05', '논문지도');

--02.
CREATE TABLE TB_학생일반정보
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT);
    
--03.
CREATE TABLE TB_국어국문학과
AS (SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", SUBSTR(STUDENT_SSN, 1, 2) + 1900 AS "출생년도", PROFESSOR_NAME AS "교수이름"
    FROM TB_STUDENT
    JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
    JOIN TB_DEPARTMENT ON (TB_STUDENT.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO)
    WHERE TB_STUDENT.DEPARTMENT_NO = (SELECT TB_DEPARTMENT.DEPARTMENT_NO
                                        FROM TB_DEPARTMENT
                                        WHERE DEPARTMENT_NAME = '국어국문학과'));
                                        
--04.
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1);

--05.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

--06.
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

--07.
UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = '200501'
    AND CLASS_NO = (SELECT CLASS_NO
                    FROM TB_CLASS
                    WHERE CLASS_NAME = '피부생리학')
    AND STUDENT_NO = (SELECT STUDENT_NO
                        FROM TB_STUDENT
                        JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                        WHERE STUDENT_NAME = '김명훈' AND DEPARTMENT_NAME = '의학과');
                        
--08.
DELETE TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');